import Link from 'next/link'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'AI Visibility Service | RocketSales Consulting',
  description: 'Get your brand cited by ChatGPT, Perplexity, Gemini, and Claude. RocketSales AI Visibility service engineers your presence into the AI answer layer.',
}

const features = [
  { title: 'AIRank Baseline Audit', desc: 'We run a full AIRank assessment across 50+ AI-relevant queries in your niche to see exactly where you are cited  and where you are not.' },
  { title: 'Citation Engineering', desc: 'We build the structured content, entity signals, and authority markers that AI models use to decide who to cite in responses.' },
  { title: 'Prompt Landscape Mapping', desc: 'We map the exact questions your ideal buyers ask AI tools, then engineer your content to answer each one definitively.' },
  { title: 'Multi-AI Coverage', desc: 'We optimize for ChatGPT, Perplexity, Google Gemini, Claude, and Microsoft Copilot  not just one platform.' },
  { title: 'Monthly AIRank Reporting', desc: 'Track your citation rate, share-of-AI-voice, and competitive position every month with clear, actionable data.' },
  { title: 'Continuous Optimization', desc: 'AI models update. We monitor changes and adapt your signals to maintain and grow your citation rate over time.' },
]

const faqs = [
  { q: 'What is AI Visibility?', a: 'AI Visibility is the practice of engineering your brand to appear in responses generated by AI tools like ChatGPT, Perplexity, and Gemini. When a buyer asks one of these tools "who should I hire for [your service]?"  AI Visibility ensures your name comes up.' },
  { q: 'How is this different from SEO?', a: 'Traditional SEO optimizes for search engine rankings. AI Visibility optimizes for AI model citations. Both are important, but they require different strategies. AI models don\'t rank pages  they synthesize answers from trusted sources.' },
  { q: 'How do you measure results?', a: 'We use AIRank  our proprietary tracking system that monitors your brand\'s citation rate across AI tools on a defined set of relevant queries. You get monthly reports showing your visibility score, trend, and competitive benchmarks.' },
  { q: 'How long does it take to see results?', a: 'Most clients see measurable improvement in AIRank within 6090 days. Full competitive dominance typically takes 46 months of consistent work.' },
]

export default function AIVisibilityPage() {
  return (
    <>
      {/* Hero */}
      <section className="py-20 bg-gradient-to-br from-purple-950 to-gray-950 text-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <p className="text-sm font-bold text-purple-400 uppercase tracking-widest mb-3">AI Visibility</p>
          <h1 className="text-5xl font-black text-white mb-6 max-w-3xl">Get Cited by ChatGPT, Perplexity & Gemini</h1>
          <p className="text-xl text-gray-300 max-w-2xl mb-8">
            When your buyers ask AI tools who to hire, your name should be the answer. We build the signals, structure, and authority that make AI models choose your brand.
          </p>
          <div className="flex flex-col sm:flex-row gap-4">
            <Link href="/contact"
              className="inline-flex items-center justify-center px-8 py-4 text-base font-bold text-white rounded-xl hover:opacity-90 transition-all"
              style={{background:'linear-gradient(135deg,#592b77,#8b4b94)'}}>
              Get Your Free AIRank Audit
            </Link>
            <Link href="/pricing"
              className="inline-flex items-center justify-center px-8 py-4 text-base font-bold text-gray-300 border-2 border-gray-600 rounded-xl hover:border-purple-400 transition-all">
              View Pricing
            </Link>
          </div>
        </div>
      </section>

      {/* What We Do */}
      <section className="py-20 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-black text-gray-900 mb-4">What AI Visibility Includes</h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">A complete system for building and tracking your presence in the AI answer layer.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((f, i) => (
              <div key={i} className="border border-gray-200 rounded-2xl p-6 hover:shadow-lg transition-all">
                <div className="w-8 h-8 rounded-lg bg-purple-100 text-purple-700 flex items-center justify-center font-black text-sm mb-4">{i + 1}</div>
                <h3 className="text-lg font-bold text-gray-900 mb-2">{f.title}</h3>
                <p className="text-gray-600 text-sm leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Why It Matters */}
      <section className="py-20 bg-gray-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-3xl font-black text-gray-900 mb-4">The AI Search Shift Is Already Happening</h2>
              <p className="text-gray-600 leading-relaxed mb-4">Over 40% of B2B buyers now use AI tools to research vendors before ever visiting a website. If you are not in those AI responses, you are invisible to a growing segment of your market.</p>
              <p className="text-gray-600 leading-relaxed">Unlike paid ads that stop when you stop paying, AI citations compound. The more AI models trust you, the more they cite you  and that trust grows over time.</p>
            </div>
            <div className="bg-gradient-to-br from-purple-950 to-gray-900 rounded-2xl p-8 text-white">
              <div className="text-4xl font-black text-orange-400 mb-2">40%+</div>
              <div className="text-white font-bold mb-4">of B2B buyers research vendors using AI</div>
              <div className="text-4xl font-black text-orange-400 mb-2">3x</div>
              <div className="text-white font-bold mb-4">higher close rate from AI-referred leads</div>
              <div className="text-4xl font-black text-orange-400 mb-2">0</div>
              <div className="text-white font-bold">cost per AI citation (vs. paid ads)</div>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ */}
      <section className="py-20 bg-white">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-black text-gray-900 mb-10 text-center">Frequently Asked Questions</h2>
          <div className="space-y-6">
            {faqs.map((faq, i) => (
              <div key={i} className="border border-gray-200 rounded-2xl p-6">
                <h3 className="text-lg font-bold text-gray-900 mb-2">{faq.q}</h3>
                <p className="text-gray-600 leading-relaxed">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 bg-gradient-to-br from-purple-950 to-gray-900 text-white text-center">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-4xl font-black mb-4">Ready to Own the AI Answer?</h2>
          <p className="text-gray-300 text-lg mb-8">Book a free 15-minute strategy call and we will run a live AIRank check on your brand  no obligation.</p>
          <Link href="/contact"
            className="inline-flex items-center justify-center px-10 py-4 text-base font-bold text-white rounded-xl hover:opacity-90 transition-all"
            style={{background:'linear-gradient(135deg,#592b77,#8b4b94)'}}>
            Book Your Free Audit
          </Link>
        </div>
      </section>
    </>
  )
}
